package population

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ReindexOptions configures the reindex behavior.
type ReindexOptions struct {
	// RootDir is the root of the vega-population repository.
	RootDir string
	// DryRun shows what would change without writing.
	DryRun bool
	// Check returns an error if any index is out of date (for CI).
	Check bool
}

// ReindexResult contains the results of a reindex operation.
type ReindexResult struct {
	PersonasAdded   []string
	PersonasRemoved []string
	SkillsAdded     []string
	SkillsRemoved   []string
	ProfilesAdded   []string
	ProfilesRemoved []string
	UpToDate        bool
}

type indexEntry struct {
	name     string
	manifest *Manifest
}

// Reindex regenerates index.yaml files from the directory contents.
func Reindex(opts *ReindexOptions) (*ReindexResult, error) {
	if opts == nil {
		opts = &ReindexOptions{}
	}

	if opts.RootDir == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return nil, fmt.Errorf("could not determine working directory: %w", err)
		}
		opts.RootDir = cwd
	}

	result := &ReindexResult{UpToDate: true}

	for _, kind := range []ItemKind{KindPersona, KindSkill, KindProfile} {
		added, removed, err := reindexKind(opts.RootDir, kind, opts.DryRun, opts.Check)
		if err != nil {
			return nil, err
		}
		if len(added) > 0 || len(removed) > 0 {
			result.UpToDate = false
		}
		switch kind {
		case KindPersona:
			result.PersonasAdded = added
			result.PersonasRemoved = removed
		case KindSkill:
			result.SkillsAdded = added
			result.SkillsRemoved = removed
		case KindProfile:
			result.ProfilesAdded = added
			result.ProfilesRemoved = removed
		}
	}

	return result, nil
}

// reindexKind regenerates the index.yaml for a single item kind.
func reindexKind(rootDir string, kind ItemKind, dryRun, check bool) (added, removed []string, err error) {
	kindDir := filepath.Join(rootDir, kind.Plural())
	indexPath := filepath.Join(kindDir, "index.yaml")

	// Scan directories for manifests
	dirEntries, err := os.ReadDir(kindDir)
	if os.IsNotExist(err) {
		return nil, nil, nil
	}
	if err != nil {
		return nil, nil, fmt.Errorf("reading %s directory: %w", kind.Plural(), err)
	}

	var entries []indexEntry
	for _, de := range dirEntries {
		if !de.IsDir() {
			continue
		}
		manifestPath := filepath.Join(kindDir, de.Name(), "vega.yaml")
		manifest, err := LoadManifest(manifestPath)
		if err != nil {
			continue
		}
		entries = append(entries, indexEntry{name: de.Name(), manifest: manifest})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})

	// Detect changes against existing index
	existingNames := make(map[string]bool)
	if content, err := os.ReadFile(indexPath); err == nil {
		existingNames = parseIndexNames(string(content))
	}

	newNames := make(map[string]bool)
	for _, e := range entries {
		newNames[e.name] = true
		if !existingNames[e.name] {
			added = append(added, e.name)
		}
	}
	for name := range existingNames {
		if !newNames[name] {
			removed = append(removed, name)
		}
	}

	if check || dryRun || (len(added) == 0 && len(removed) == 0) {
		return added, removed, nil
	}

	// Write updated index
	content := buildIndex(kind, entries)
	if err := os.WriteFile(indexPath, []byte(content), 0644); err != nil {
		return nil, nil, fmt.Errorf("writing %s: %w", indexPath, err)
	}

	return added, removed, nil
}

// buildIndex generates the index.yaml content for a kind.
func buildIndex(kind ItemKind, entries []indexEntry) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Vega Population - %s Index\n", titleCase(kind.Plural())))
	b.WriteString("# Auto-generated by: vega population reindex\n\n")
	b.WriteString(fmt.Sprintf("%s:\n", kind.Plural()))

	for _, entry := range entries {
		m := entry.manifest
		b.WriteString(fmt.Sprintf("  %s:\n", entry.name))
		b.WriteString(fmt.Sprintf("    version: %s\n", m.Version))
		b.WriteString(fmt.Sprintf("    description: %s\n", m.Description))
		b.WriteString(fmt.Sprintf("    author: %s\n", m.Author))

		if kind == KindProfile {
			if m.Persona != "" {
				b.WriteString(fmt.Sprintf("    persona: %s\n", m.Persona))
			}
			if len(m.Skills) > 0 {
				b.WriteString(fmt.Sprintf("    skills: [%s]\n", strings.Join(m.Skills, ", ")))
			}
		} else {
			if len(m.Tags) > 0 {
				b.WriteString(fmt.Sprintf("    tags: [%s]\n", strings.Join(m.Tags, ", ")))
			}
			if kind == KindSkill && len(m.Tools) > 0 {
				var names []string
				for _, t := range m.Tools {
					names = append(names, t.Name)
				}
				b.WriteString(fmt.Sprintf("    tools: [%s]\n", strings.Join(names, ", ")))
			}
		}
		b.WriteString("\n")
	}

	return b.String()
}

// parseIndexNames extracts item names from an existing index file.
// Names are at 2-space indent with a trailing colon and no value.
func parseIndexNames(content string) map[string]bool {
	names := make(map[string]bool)
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "  ") && !strings.HasPrefix(line, "    ") {
			trimmed := strings.TrimSpace(line)
			if strings.HasSuffix(trimmed, ":") && !strings.Contains(trimmed, " ") {
				names[strings.TrimSuffix(trimmed, ":")] = true
			}
		}
	}
	return names
}
